var products = [
  [1, "Pet", "MÈO ANH LÔNG NGẮN", ""],
  [2, "Pet", "CHÓ CORKI", ""],
  [3, "Pet", "MÈO MUNCHKIN", ""],
  [4, "Pet", "MÈO ANH LÔNG DÀI", ""],
  [5, "pet", "MÈO BA TƯ", ""],
  [6, "pet", "MÈO MAINE COON", ""],
  [7, "pet", "MÈO ANH CHÂN NGẮN TAI CỤT", ""],
  [8, "pet", "MÈO KHÔNG LÔNG SPHYNX", ""],
  [9, "pet", "MÈO XIÊM", ""],
  [10, "pet", "CHÓ HUSKY", ""],
  [11, "pet", "CHÓ ALASKA", ""],
  [12, "pet", "CHÓ HMONG CỘC", ""],
  [13, "pet", "CHÓ BORDER COLLIE", ""],
  [14, "pet", "CHÓ SAMOYED", ""],
  [15, "pet", "CHÓ CHOW CHOW", ""],
  [16, "pet", "CHÓ BULL PHÁP", ""],
  [17, "pet", "CHÓ BULLDOG ANH", ""],
  [18, "vật dụng", "BALO VUÔNG NHỰA DẺO", "350.000đ"],
  [19, "vật dụng", "SỬA TẮM CHÓ MÈO BIO", "210.000đ"],
  [20, "vật dụng", "RỌ MÕ CHÓ BẰNG NHỰA", "95.000đ"],
  [21, "vật dụng", "TRỤ CÀO MÈO TREO CON CHUỘT", "140.000đ"],
];
export default products;
